/*

 EXPLOREBKGTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 28
   Tile set      : D:\Dev\Gameboy\GGJ2024\Src\Assets\Backgrounds\ExploreBkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ExploreBkgTileMapWidth 30
#define ExploreBkgTileMapHeight 28
#define ExploreBkgTileMapBank 0

extern unsigned char ExploreBkgTileMap[];

/* End of EXPLOREBKGTILEMAP.H */
