/*

 EXPLOREHALLTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 36 x 26
   Tile set      : D:\Dev\Gameboy\GGJ2024\Src\Assets\Backgrounds\ExploreBkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ExploreHallTileMapWidth 36
#define ExploreHallTileMapHeight 26
#define ExploreHallTileMapBank 0

extern unsigned char ExploreHallTileMap[];

/* End of EXPLOREHALLTILEMAP.H */
