/*

 EXPLOREBARRACKSTILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 26
   Tile set      : D:\Dev\Gameboy\GGJ2024\Src\Assets\Backgrounds\ExploreBkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ExploreBarracksTileMapWidth 30
#define ExploreBarracksTileMapHeight 26
#define ExploreBarracksTileMapBank 0

extern unsigned char ExploreBarracksTileMap[];

/* End of EXPLOREBARRACKSTILEMAP.H */
